pipeline{
    agent any
    environment{
        DOCKER_PASS = credentials('docker_password')
    }
    stages{
        stage('test'){
            agent{docker 'node:18-alpine3.16'}
            steps{
                sh 'npm install'
                sh 'npm test'
            }
            post{
                always{
                    archiveArtifacts artifacts: 'tests/test-results/', followSymlinks: false
                }
            }
        }
        stage('Package'){
            steps{
                sh 'docker build -t at20_questionnaire_service .'
            }
        }

        stage('Publish'){
            steps{
                sh 'docker login -u dkmar11 -p ${DOCKER_PASS}'
                sh 'docker tag at20_questionnaire_service israel/questionnaire'
                sh 'docker push israel/questionnaire'
            }
        }
    }
}